name: Publish to WordPress SVN

on:
  push:
    tags:
    - "v*"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout the code from the repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # 2. Run the WordPress Plugin Deploy action
      - name: WordPress Plugin Deploy
        uses: nk-o/action-wordpress-plugin-deploy@master
        env:
          SVN_PASSWORD: ${{ secrets.SVN_PASSWORD }}
          SVN_USERNAME: ${{ secrets.SVN_USERNAME }}
          SOURCE_DIR: 
          SLUG: social-integration-for-bluesky